// <auto-generated />
using System;
using MegaDeskWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MegaDeskWebApp.Migrations
{
    [DbContext(typeof(MegaDeskWebAppContext))]
    [Migration("20191108010302_Initial-migration")]
    partial class Initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MegaDeskWebApp.Models.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("depth");

                    b.Property<int?>("desktopMaterial");

                    b.Property<int>("drawerNum");

                    b.Property<string>("materialType")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("rushDays");

                    b.Property<int>("width");

                    b.HasKey("ID");

                    b.ToTable("Desk");
                });

            modelBuilder.Entity("MegaDeskWebApp.Models.DeskQuote", b =>
                {
                    b.Property<int>("DeskQuoteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("deskID");

                    b.Property<int>("drawerCost");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("materialCost");

                    b.Property<DateTime>("purchaseDate");

                    b.Property<int>("rushCost");

                    b.Property<int>("sizeCost");

                    b.Property<int>("totalCost");

                    b.HasKey("DeskQuoteID");

                    b.HasIndex("deskID");

                    b.ToTable("DeskQuote");
                });

            modelBuilder.Entity("MegaDeskWebApp.Models.DeskQuote", b =>
                {
                    b.HasOne("MegaDeskWebApp.Models.Desk", "desk")
                        .WithMany("deskQuotes")
                        .HasForeignKey("deskID");
                });
#pragma warning restore 612, 618
        }
    }
}
